# Generated by Django 5.1.7 on 2025-04-19 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="客户名称")),
                (
                    "contact",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批号"),
                ),
                (
                    "model_spec",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="型号规格"
                    ),
                ),
                (
                    "pin_pitch",
                    models.CharField(blank=True, max_length=50, verbose_name="针距"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="供应商名称")),
                (
                    "contact",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
            },
        ),
        migrations.CreateModel(
            name="BatchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批号")),
                ("model_number", models.CharField(max_length=100, verbose_name="型号")),
                (
                    "pin_pitch",
                    models.CharField(blank=True, max_length=50, verbose_name="针距"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "批次组",
                "verbose_name_plural": "批次组",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="模型名称"),
                ),
                ("object_id", models.IntegerField(verbose_name="对象ID")),
                ("action", models.CharField(max_length=50, verbose_name="操作类型")),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="变更内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="型号名称")),
                ("model_number", models.CharField(max_length=100, verbose_name="型号")),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=50, verbose_name="条形码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品型号",
                "verbose_name_plural": "产品型号",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="生效日期"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                        verbose_name="产品型号",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格记录",
                "verbose_name_plural": "价格记录",
            },
        ),
        migrations.CreateModel(
            name="OutgoingShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="单据编号"),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批号")),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="总金额"
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("APPROVED", "已审核"),
                            ("REJECTED", "已驳回"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                        verbose_name="产品型号",
                    ),
                ),
            ],
            options={
                "verbose_name": "出货单据",
                "verbose_name_plural": "出货单据",
            },
        ),
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批号")),
                (
                    "change_type",
                    models.CharField(
                        choices=[("IN", "入库"), ("OUT", "出库")],
                        max_length=3,
                        verbose_name="变动类型",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="变动数量")),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="单据编号"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变动时间"),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                        verbose_name="产品型号",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存变动记录",
                "verbose_name_plural": "库存变动记录",
            },
        ),
        migrations.CreateModel(
            name="IncomingShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="单据编号"),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批号")),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "shipment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="来料日期"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("APPROVED", "已审核"),
                            ("REJECTED", "已驳回"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                        verbose_name="产品型号",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "来料单据",
                "verbose_name_plural": "来料单据",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批号")),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="存储位置"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                        verbose_name="产品型号",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
                "unique_together": {("product_type", "batch_number")},
            },
        ),
    ]
