# Generated by Django 4.2.20 on 2025-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='批号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='model_spec',
            field=models.CharField(blank=True, max_length=100, verbose_name='品名规格'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pin_pitch',
            field=models.CharField(blank=True, max_length=50, verbose_name='脚距'),
        ),
        migrations.AddField(
            model_name='customer',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价'),
        ),
    ]
