# Generated by Django 5.1.7 on 2025-04-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                        verbose_name="产品型号",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格记录",
                "verbose_name_plural": "价格记录",
            },
        ),
        migrations.CreateModel(
            name="BatchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批号")),
                ("model_number", models.CharField(max_length=100, verbose_name="型号")),
                ("pin_pitch", models.CharField(max_length=50, verbose_name="脚距")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "批次组",
                "verbose_name_plural": "批次组",
                "unique_together": {("customer", "batch_number", "model_number")},
            },
        ),
    ]
