# Generated by Django 5.1.7 on 2025-04-19 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_outgoingshipment_batch_group_outgoingshipment_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingshipment",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="选单号码"),
        ),
        migrations.AddField(
            model_name="outgoingshipment",
            name="shipment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="出货日期"
            ),
        ),
    ]
