# Generated by Django 4.2.20 on 2025-04-18 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_batch_number_customer_model_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingshipment',
            name='batch_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batchgroup', verbose_name='批次组'),
        ),
        migrations.AddField(
            model_name='outgoingshipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='outgoingshipment',
            name='shipping_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出货日期'),
        ),
    ]
