# Generated by Django 4.2.20 on 2025-04-18 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_outgoingshipment_batch_group_outgoingshipment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingshipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='incomingshipment',
            name='shipment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='来料日期'),
        ),
    ]
