# Generated by Django 5.1.7 on 2025-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_outgoingshipment_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingshipment",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="供应商"
            ),
        ),
    ]
