# Generated by Django 4.2.20 on 2025-04-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_incomingshipment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价'),
        ),
    ]
