# Generated by Django 5.1.7 on 2025-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_incomingshipment_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingshipment",
            name="product_spec",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="品名规格"
            ),
        ),
    ]
