# Generated by Django 5.1.7 on 2025-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_outgoingshipment_product_spec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoingshipment",
            name="batch_group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="批次组"
            ),
        ),
    ]
