# Generated by Django 4.2.20 on 2025-04-18 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_producttype_customer_producttype_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingshipment',
            name='customer_part_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='客户料号'),
        ),
        migrations.AddField(
            model_name='outgoingshipment',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单重(g)'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='条形码'),
        ),
    ]
