# Generated by Django 5.1.7 on 2025-04-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_outgoingshipment_batch_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outgoingshipment",
            old_name="batch_group",
            new_name="batch_group_name",
        ),
    ]
