# Generated by Django 4.2.20 on 2025-04-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_outgoingshipment_customer_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingshipment',
            name='customer_part_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='选单号码'),
        ),
        migrations.AlterField(
            model_name='outgoingshipment',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype', verbose_name='品名规格'),
        ),
    ]
