# Generated by Django 4.2.10 on 2025-04-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_batch_group_outgoingshipment_batch_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='outgoingshipment',
            name='batch_group_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='批次组'),
        ),
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('delivery_number', models.CharField(max_length=50, verbose_name='送单号码')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('foot_distance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='脚距')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单重')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='客户')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype', verbose_name='产品型号')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
                'ordering': ['-date'],
            },
        ),
    ]
