# Generated by Django 4.2.20 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_outgoingshipment_customer_part_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingshipment',
            name='document_number',
        ),
        migrations.AlterField(
            model_name='outgoingshipment',
            name='product_type',
            field=models.CharField(max_length=100, verbose_name='品名规格'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='model_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='品名'),
        ),
    ]
