# Generated by Django 4.2.20 on 2025-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_outgoingshipment_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingshipment',
            name='pin_pitch',
            field=models.CharField(blank=True, max_length=50, verbose_name='脚距'),
        ),
        migrations.AlterField(
            model_name='outgoingshipment',
            name='batch_group',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='批次组'),
        ),
    ]
