# Generated by Django 4.2.20 on 2025-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_outgoingshipment_pin_pitch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingshipment',
            name='product_spec',
            field=models.CharField(blank=True, max_length=200, verbose_name='品名规格'),
        ),
    ]
