# Generated by Django 4.2.20 on 2025-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_product_spec_field'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Rename original table to temporary table
            ALTER TABLE inventory_outgoingshipment RENAME TO inventory_outgoingshipment_old;
            
            -- Create new table with correct structure
            CREATE TABLE inventory_outgoingshipment (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                shipping_date DATE NOT NULL,
                batch_number VARCHAR(50) NOT NULL,
                batch_group VARCHAR(50) DEFAULT '' NOT NULL,
                quantity INTEGER NOT NULL,
                unit_weight DECIMAL(10, 2) DEFAULT 0 NOT NULL,
                unit_price DECIMAL(10, 2) NOT NULL,
                total_amount DECIMAL(12, 2) DEFAULT 0 NOT NULL,
                notes TEXT DEFAULT '' NOT NULL,
                audit_status VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
                created_at DATETIME NOT NULL,
                audit_time DATETIME NULL,
                auditor_id INTEGER NULL REFERENCES auth_user (id),
                customer_id INTEGER NOT NULL REFERENCES inventory_customer (id),
                pin_pitch VARCHAR(50) DEFAULT '' NOT NULL,
                product_spec VARCHAR(200) DEFAULT '' NOT NULL,
                customer_part_number VARCHAR(50) DEFAULT '' NOT NULL,
                product_type_id INTEGER NOT NULL REFERENCES inventory_producttype (id)
            );
            
            -- Copy data from old table to new table
            INSERT INTO inventory_outgoingshipment (id, shipping_date, batch_number, batch_group, quantity, unit_weight, unit_price, total_amount, notes, audit_status, created_at, audit_time, auditor_id, customer_id, pin_pitch, product_spec, customer_part_number, product_type_id)
            SELECT id, shipping_date, batch_number, batch_group, quantity, unit_weight, unit_price, total_amount, notes, audit_status, created_at, audit_time, auditor_id, customer_id, pin_pitch, '', customer_part_number, 
            -- 使用一个默认的product_type_id（使用第一个可用的product_type）
            (SELECT id FROM inventory_producttype LIMIT 1)
            FROM inventory_outgoingshipment_old;
            
            -- Drop the old table
            DROP TABLE inventory_outgoingshipment_old;
            """,
            """
            -- Reverse SQL migration (rollback)
            -- Not implemented
            """,
        ),
    ] 