# Generated by Django 4.2.20 on 2025-04-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_revert_outgoingshipment_fields'),
        ('inventory', '0011_add_missing_fields'),
    ]

    operations = [
    ]
